name: RMT
favicon: null
layout_spectrum: 0.08740050811320543
typography_spectrum: 0.8719006879255176
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9905054022092372
  lightness: 0.22821159358136356
  saturation: 0.7383662257343531
  rhythmicContrast: 0.4316416347865015
purpose: []
